# SPDX-FileCopyrightText: 2020 Florian Vuillemot <florian.vuillemot@posteo.net>
#
# SPDX-License-Identifier: GPL-3.0-or-later

FROM python:3.6

RUN pip install mock-server

EXPOSE 8888

COPY ./config /config

CMD mock-server --dir=/config -address=0.0.0.0
