# =============================================================================
# Continuous Delivery instructions
# =============================================================================
# This file is part of the FSFE Form Server.
#
# SPDX-FileCopyrightText: 2020 FSFE e.V. <contact@fsfe.org>
#
# SPDX-License-Identifier: GPL-3.0-or-later

pipeline:
  build-quality:
    image: tmaier/docker-compose
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    commands:
      - docker-compose --file docker-compose-quality.yml build

  quality:
    image: fsfe-forms-quality
    commands:
      - isort --check-only --diff
      - pylama
      - pytest

  deploy:
    image: tmaier/docker-compose
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    commands:
      - docker-compose build
      - docker-compose up -d
    when:
       event:
         - push
         - tag
         - deployment
       branch: master
