# =============================================================================
# Deployment instructions for the developer's Docker container
# =============================================================================
# This file is part of the FSFE Form Server.
#
# SPDX-FileCopyrightText: 2020 FSFE e.V. <contact@fsfe.org>
# SPDX-FileCopyrightText: 2019 Florian Vuillemot <florian.vuillemot@fsfe.org>
#
# SPDX-License-Identifier: GPL-3.0-or-later

version: "3"
services:
  forms-redis:
    image: bitnami/redis:6.2
    container_name: forms-redis
    expose:
      - "6379"
    environment:
      ALLOW_EMPTY_PASSWORD: "yes"
    restart: always

  # This is the container for local testing
  forms-quality:
    image: forms-quality
    container_name: forms-quality
    build:
      dockerfile: Dockerfile-quality
      target: development
      args:
        user_id: "${USER_ID}"
        group_id: "${GROUP_ID}"
    volumes:
      - ".:/home/fsfe/src"
    command: sleep infinity

  forms:
    image: forms
    container_name: forms
    build:
      target: development
      context: .
    depends_on:
      - forms-redis
    ports:
      - "8080:8080"
    volumes:
      - ".:/home/fsfe/src"
      - "./store:/store:rw"
    restart: always
    environment:
      FLASK_APP: "/home/fsfe/src/fsfe_forms"
      FLASK_DEBUG: "True"
      FLASK_RUN_HOST: "0.0.0.0"
      FLASK_RUN_PORT: 8080
      LOG_EMAIL_FROM: "contact@fsfe.org"
      LOG_EMAIL_TO: "contact@fsfe.org"
      MAIL_PORT: "1025"
      MAIL_SERVER: "forms-maildev"
      REDIS_HOST: "forms-redis"
      REDIS_PORT: "6379"
      VALIDATE_EMAIL_FROM: "contact@fsfe.org"
      FSFE_CD_URL: "http://forms-fake-fsfe-cd-front:8888/"
    command: /bin/sh -c "flask run"

  forms-maildev:
    image: maildev/maildev:2.0.5
    container_name: forms-maildev
    ports:
      - "1025:1025"
      - "1080:1080"

  forms-fake-fsfe-cd-front:
    image: forms-fake-fsfe-cd-front
    build:
      context: ./forms-fake-fsfe-cd-front
      dockerfile: Dockerfile-fake-fsfe-cd-front
    container_name: forms-fake-fsfe-cd-front
    ports:
      - "8888:8888"
