# =============================================================================
# Deployment instructions for the developer's Docker container
# =============================================================================
# This file is part of the FSFE Form Server.
#
# SPDX-FileCopyrightText: 2020 FSFE e.V. <contact@fsfe.org>
# SPDX-FileCopyrightText: 2019 Florian Vuillemot <florian.vuillemot@fsfe.org>
#
# SPDX-License-Identifier: GPL-3.0-or-later

services:
  forms:
    container_name: forms
    image: forms
    restart: always
    depends_on:
      - forms-redis
    build:
      context: .
      target: development
    ports:
      - "8080:8080"
    environment:
      FLASK_APP: "/home/fsfe/src/fsfe_forms"
      FLASK_DEBUG: "True"
      FLASK_RUN_HOST: "0.0.0.0"
      FLASK_RUN_PORT: 8080
      LOG_EMAIL_FROM: "contact@fsfe.org"
      LOG_EMAIL_TO: "contact@fsfe.org"
      MAIL_PORT: "1025"
      MAIL_SERVER: "forms-maildev"
      REDIS_HOST: "forms-redis"
      REDIS_PORT: "6379"
      VALIDATE_EMAIL_FROM: "contact@fsfe.org"
      FSFE_CD_URL: "http://forms-fake-fsfe-cd-front:8888/"
    volumes:
      - ".:/home/fsfe/src"
      - "./store:/store:rw"
    command: /bin/sh -c "flask run"

  forms-redis:
    container_name: forms-redis
    image: redis:8-alpine
    restart: always
    expose:
      - "6379"

  forms-maildev:
    image: maildev/maildev:2.2.1
    container_name: forms-maildev
    ports:
      - "1025:1025"
      - "1080:1080"

  forms-fake-fsfe-cd-front:
    image: forms-fake-fsfe-cd-front
    build:
      context: ./forms-fake-fsfe-cd-front
      dockerfile: Dockerfile
    container_name: forms-fake-fsfe-cd-front
    ports:
      - "8888:8888"

  # This is the container for local testing
  forms-quality:
    container_name: forms-quality
    image: forms-quality
    build:
      dockerfile: Dockerfile.quality
      target: development
      args:
        user_id: "${USER_ID}"
        group_id: "${GROUP_ID}"
    volumes:
      - ".:/home/fsfe/src"
    command: sleep infinity
