# =============================================================================
# Build instructions for the quality check Docker container
# =============================================================================
# This file is part of the FSFE Form Server.
#
# SPDX-FileCopyrightText: 2020 FSFE e.V. <contact@fsfe.org>
#
# SPDX-License-Identifier: GPL-3.0-or-later

FROM bitnami/python:3.9

WORKDIR /root

# Install Python packages
COPY requirements_all.txt ./
RUN pip install --ignore-installed setuptools pip
RUN pip install --no-cache-dir -r requirements_all.txt
