# =============================================================================
# Deployment instructions for the Docker container
# =============================================================================
# This file is part of the FSFE Form Server.
#
# SPDX-FileCopyrightText: 2017-2019 Free Software Foundation Europe <contact@fsfe.org>
# SPDX-FileCopyrightText: 2019 Florian Vuillemot <florian.vuillemot@fsfe.org>
#
# SPDX-License-Identifier: GPL-3.0-or-later

version: '3'
services:
  forms-redis:
    image: redis:3.2
    container_name: forms-redis
    labels:
      fsfe-monitoring: "true"
    expose:
      - 6379
    restart: always

  forms:
    depends_on:
      - forms-redis
    image: forms
    build: .
    container_name: forms
    labels:
      fsfe-monitoring: "true"
    environment:
      VIRTUAL_HOST: "forms.fsfe.org"
      LETSENCRYPT_HOST: "forms.fsfe.org"
      LETSENCRYPT_EMAIL: "contact@fsfe.org"
      RATELIMIT_DEFAULT: "1 per second, 5 per minute, 20 per hour"
      MAIL_SERVER: "mail.fsfe.org"
      LOG_EMAIL_FROM: "contact@fsfe.org"
      LOG_EMAIL_TO: "contact@fsfe.org"
      REDIS_HOST: "forms-redis"
      REDIS_PORT: "6379"
    volumes:
      - "/srv/forms:/store:rw"
    restart: always

  connect-bridge:
    depends_on:
      - forms
    image: docker:dind
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: docker network connect bridge forms
