# =============================================================================
# Deployment instructions for the developer's Docker container
# =============================================================================
# This file is part of the FSFE Form Server.
#
# SPDX-FileCopyrightText: 2017-2019 Free Software Foundation Europe <contact@fsfe.org>
# SPDX-FileCopyrightText: 2019 Florian Vuillemot <florian.vuillemot@fsfe.org>
#
# SPDX-License-Identifier: GPL-3.0-or-later

version: '3'
services:
  forms:
    ports:
      - "8080:8080"
    environment:
      "MAIL_SERVER": "forms-fakesmtp"
      "MAIL_PORT": "1025"
      "LOG_EMAIL_FROM": "contact@fsfe.org"
      "LOG_EMAIL_TO": "contact@fsfe.org"

  forms-fakesmtp:
    image: forms-fakesmtp
    build:
      context: ./fake-smtp-server
      dockerfile: Dockerfile-smtp
    container_name: forms-fakesmtp
    ports:
      - "1025:1025"
      - "1080:1080"
