# =============================================================================
# Build instructions for the quality check Docker container
# =============================================================================
# This file is part of the FSFE Form Server.
#
# SPDX-FileCopyrightText: 2017-2019 Free Software Foundation Europe <contact@fsfe.org>
#
# SPDX-License-Identifier: GPL-3.0-or-later

FROM fsfe/alpine-pipenv:latest

WORKDIR /root

# Install Python packages
COPY Pipfile Pipfile.lock ./
RUN pipenv install --system --deploy --dev
