# =============================================================================
# Deployment instructions for the Docker container
# =============================================================================
# This file is part of the FSFE Form Server.
#
# SPDX-FileCopyrightText: 2020 FSFE e.V. <contact@fsfe.org>
# SPDX-FileCopyrightText: 2019 Florian Vuillemot <florian.vuillemot@fsfe.org>
#
# SPDX-License-Identifier: GPL-3.0-or-later

version: "3"
services:
  forms-redis:
    image: redis:3.2
    container_name: forms-redis
    expose:
      - 6379
    restart: always

  forms:
    depends_on:
      - forms-redis
    image: forms
    build: .
    container_name: forms
    labels:
      proxy.host: "forms.fsfe.org"
      proxy.port: "870"
    environment:
      VIRTUAL_HOST: "forms.fsfe.org"
      LETSENCRYPT_HOST: "forms.fsfe.org"
      LETSENCRYPT_EMAIL: "contact@fsfe.org"
      RATELIMIT_DEFAULT: "1 per second, 5 per minute, 20 per hour"
      MAIL_SERVER: "mail.fsfe.org"
      LOG_EMAIL_FROM: "contact@fsfe.org"
      LOG_EMAIL_TO: "contact@fsfe.org"
      REDIS_HOST: "forms-redis"
      REDIS_PORT: "6379"
      FSFE_CD_URL: "https://my.fsfe.org/"
      FSFE_CD_TIMEOUT: 3
      FSFE_CD_PASSPHRASE: "${FSFE_CD_PASSPHRASE}"
    volumes:
      - "/srv/forms:/store:rw"
    restart: always

  connect-bridge:
    depends_on:
      - forms
    image: docker:dind
    volumes:
      - /run/user/1001/docker.sock:/var/run/docker.sock
    command: docker network connect bridge forms
