version: '3'
services:

  forms-web:
    ports:
    - "8080:8080"
    environment:
    - SMTP_HOST=forms-fakesmtp
    - SMTP_PORT=1025

  forms-fakesmtp:
    container_name: forms-fakesmtp
    build:
      context: ./fake-smtp-server
      dockerfile: Dockerfile-smtp
    image: forms-fakesmtp
    ports:
    - "1025:1025"
    - "1080:1080"
