# =============================================================================
# Build instructions for the quality check Docker container
# =============================================================================
# This file is part of the FSFE Form Server.
#
# SPDX-FileCopyrightText: 2020 FSFE e.V. <contact@fsfe.org>
#
# SPDX-License-Identifier: GPL-3.0-or-later

FROM bitnami/python:3.9

RUN pip3 install --no-cache-dir -U pip
RUN pip3 install --no-cache-dir -U pipenv

WORKDIR /root

# Install Python packages
COPY Pipfile Pipfile.lock ./
RUN pipenv install --system --deploy --dev
