# =============================================================================
# Deployment instructions for the quality check Docker container
# =============================================================================
# This file is part of the FSFE Form Server.
#
# SPDX-FileCopyrightText: 2017-2019 Free Software Foundation Europe <contact@fsfe.org>
#
# SPDX-License-Identifier: GPL-3.0-or-later

version: "3"
services:
  fsfe-forms-quality:
    image: fsfe-forms-quality
    build:
      context: .
      dockerfile: Dockerfile-quality
