# =============================================================================
# Deployment instructions for the Docker container
# =============================================================================
# This file is part of the FSFE Form Server.
#
# SPDX-FileCopyrightText: 2020 FSFE e.V. <contact@fsfe.org>
# SPDX-FileCopyrightText: 2019 Florian Vuillemot <florian.vuillemot@fsfe.org>
#
# SPDX-License-Identifier: GPL-3.0-or-later

version: "3"
services:
  forms-redis:
    image: redis:6
    container_name: forms-redis
    expose:
      - 6379
    restart: always

  forms:
    depends_on:
      - forms-redis
    image: forms
    build:
      target: production
      context: .
    container_name: forms
    environment:
      RATELIMIT_DEFAULT: "5 per second, 50 per minute, 2000 per hour"
      MAIL_SERVER: "mail.fsfe.org"
      MAIL_HELO_HOST: "cont2.noris.fsfeurope.org"
      LOG_EMAIL_FROM: "contact@fsfe.org"
      VALIDATE_EMAIL_HELO: "cont2.noris.fsfeurope.org"
      VALIDATE_EMAIL_FROM: "contact@fsfe.org"
      LOG_EMAIL_TO: "contact@fsfe.org"
      REDIS_HOST: "forms-redis"
      REDIS_PORT: "6379"
      FSFE_CD_URL: "https://my.fsfe.org/"
      FSFE_CD_TIMEOUT: 3
      FSFE_CD_PASSPHRASE: "${FSFE_CD_PASSPHRASE}"
    volumes:
      - "/srv/forms:/store:rw"
    restart: always
    # Reverse Proxy
    labels:
      proxy.host: "forms.fsfe.org"
      proxy.port: "870"
    ports:
      - "870:8080"
