---
- hosts: lund.fsfeurope.org
  remote_user: root

  tasks:
    - name: run nginx proxy
      docker_container:
        name: nginx-proxx
        image: nginx
        state: started
        restart: yes
        env:
          VIRTUAL_HOST: forms.fsfe.org
          LETSENCRYPT_HOST: forms.fsfe.org
          LETSENCRYPT_EMAIL: jonas@fsfe.org

    - name: build the container
      command: docker build -f Dockerfile-web -t forms https://git.fsfe.org/FSFE/forms.git

    - name: run web app
      docker_container:
        name: forms
        image: forms
        state: started
        restart: yes