---
- hosts: lund.fsfeurope.org
  remote_user: root

  tasks:
    - name: build web application
      command: docker build -f Dockerfile-web -t forms-web https://git.fsfe.org/FSFE/forms.git

    - name: start redis
      docker_container:
        name: redis
        image: redis:3.2
        state: started
        exposed_ports:
          - "6379"
    - name: run web app
      docker_container:
        name: web-app
        image: forms-web
        env:
          REDIS_HOST: "redis"
          REDIS_PORT: 6379