---
- hosts: lund.fsfeurope.org
  remote_user: root

  tasks:
    - name: build web container
      command: docker build -f Dockerfile-web -t forms-web https://git.fsfe.org/FSFE/forms.git

    - name: build worker container
      command: docker build -f Dockerfile-worker -t forms-worker https://git.fsfe.org/FSFE/forms.git

    - name: create network
      docker_network:
        name: FormsNet

    - name: run redis
      docker_container:
        name: redis
        image: redis:3.2
        state: started
        restart: yes
        #command: redis-server --requirepass {{REDIS_PASSWORD}}
        networks:
          - name: FormsNet

    - name: run web app
      docker_container:
        name: forms-web
        image: forms-web
        state: started
        restart: yes
        exposed_ports:
          - 8080
        env:
          REDIS_HOST: "formsredis"
          REDIS_PORT: 6379
          #REDIS_PASSWORD: "{{REDIS_PASSWORD}}"
          VIRTUAL_HOST: forms.fsfe.org
          LETSENCRYPT_HOST: forms.fsfe.org
          LETSENCRYPT_EMAIL: jonas@fsfe.org
        networks:
          - name: FormsNet
            links:
              - "redis:formsredis"
        volumes:
          - "/srv/forms:/store:rw"

    - name: run worker app
      docker_container:
        name: forms-worker
        image: forms-worker
        state: started
        restart: yes
        env:
          REDIS_HOST: "formsredis"
          REDIS_PORT: 6379
          #REDIS_PASSWORD: "{{REDIS_PASSWORD}}"
          SMTP_HOST: "mail.fsfe.org"
          SMTP_PORT: 25
        networks:
          - name: FormsNet
            links:
              - "redis:formsredis"
        volumes:
          - "/srv/forms:/store:rw"
