---
- hosts: lund.fsfeurope.org
  remote_user: root

  tasks:
    - name: build the container
      docker_service:
        project_src: .
        build: yes

    - name: run
      docker_service:
        project_src: .
        build: no
        env:
          VIRTUAL_HOST: forms.fsfe.org
          LETSENCRYPT_HOST: forms.fsfe.org
          LETSENCRYPT_EMAIL: jonas@fsfe.org
