---
- hosts: lund.fsfeurope.org
  remote_user: root

  tasks:
    - name: build the container
      command: docker build -f Dockerfile-web -t forms https://git.fsfe.org/FSFE/forms.git

    - name: run
      docker_container:
        name: forms
        image: forms
        state: started
        restart: yes
        published_ports:
          - "forms.fsfe.org:80:8080"
        env:
          VIRTUAL_HOST: forms.fsfe.org
          LETSENCRYPT_HOST: forms.fsfe.org
          LETSENCRYPT_EMAIL: jonas@fsfe.org