---
- hosts: lund.fsfeurope.org
  remote_user: root

  tasks:
    - name: install docker compose
      command: pip install docker-compose

    - name: run
      docker_service:
        build: yes
        state: present
        project_src: .
        project_name: forms
