from common.config import REDIS_HOST, REDIS_PORT

BROKER_URL = 'redis://%s:%s' % (REDIS_HOST, REDIS_PORT)
CELERY_RESULT_BACKEND = BROKER_URL
CELERY_ACCEPT_CONTENT = ['json']
CELERY_TASK_SERIALIZER = 'json'
CELERY_RESULT_SERIALIZER = 'json'
CELERY_DEFAULT_QUEUE = 'email_queue'
